openapi: 3.1.0
info:
  description: Production ready AI assistant framework
  title: ðŸ˜¸ Cheshire-Cat API
  version: 1.7.1
  x-logo:
    url: https://cheshirecat.ai/wp-content/uploads/2023/10/Logo-Cheshire-Cat.svg
servers:
- url: /
paths:
  /:
    get:
      description: Server status
      operationId: home
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Home
                type: object
          description: Successful Response
      summary: Home
      tags:
      - Status
      x-accepts:
      - application/json
  /message:
    post:
      description: Get a response from the Cat
      operationId: message_with_cat
      requestBody:
        content:
          application/json:
            schema:
              default:
                text: hello!
              title: Payload
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatMessage'
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Message With Cat
      tags:
      - Status
      x-content-type: application/json
      x-accepts:
      - application/json
  /auth/available-permissions:
    get:
      description: Returns all available resources and permissions.
      operationId: get_available_permissions
      responses:
        "200":
          content:
            application/json:
              schema:
                additionalProperties:
                  items:
                    $ref: '#/components/schemas/AuthPermission'
                title: Response Get Available Permissions
          description: Successful Response
      summary: Get Available Permissions
      tags:
      - User Auth
      x-accepts:
      - application/json
  /auth/token:
    post:
      description: |-
        Endpoint called from client to get a JWT from local identity provider.
        This endpoint receives username and password as form-data, validates credentials and issues a JWT.
      operationId: auth_token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCredentials'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWTResponse'
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Auth Token
      tags:
      - User Auth
      x-content-type: application/json
      x-accepts:
      - application/json
  /users/:
    get:
      operationId: read_users
      parameters:
      - explode: true
        in: query
        name: skip
        required: false
        schema:
          default: 0
          title: Skip
          type: integer
        style: form
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 100
          title: Limit
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/UserResponse'
                type: array
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Read Users
      tags:
      - Users
      x-accepts:
      - application/json
    post:
      operationId: create_user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Create User
      tags:
      - Users
      x-content-type: application/json
      x-accepts:
      - application/json
  /users/{user_id}:
    delete:
      operationId: delete_user
      parameters:
      - explode: false
        in: path
        name: user_id
        required: true
        schema:
          title: User Id
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Delete User
      tags:
      - Users
      x-accepts:
      - application/json
    get:
      operationId: read_user
      parameters:
      - explode: false
        in: path
        name: user_id
        required: true
        schema:
          title: User Id
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Read User
      tags:
      - Users
      x-accepts:
      - application/json
    put:
      operationId: update_user
      parameters:
      - explode: false
        in: path
        name: user_id
        required: true
        schema:
          title: User Id
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Update User
      tags:
      - Users
      x-content-type: application/json
      x-accepts:
      - application/json
  /settings/:
    get:
      description: Get the entire list of settings available in the database
      operationId: get_settings
      parameters:
      - explode: true
        in: query
        name: search
        required: false
        schema:
          default: ""
          title: Search
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Settings
      tags:
      - Settings
      x-accepts:
      - application/json
    post:
      description: Create a new setting in the database
      operationId: create_setting
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SettingBody'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Create Setting
      tags:
      - Settings
      x-content-type: application/json
      x-accepts:
      - application/json
  /settings/{settingId}:
    delete:
      description: Delete a specific setting in the database
      operationId: delete_setting
      parameters:
      - explode: false
        in: path
        name: settingId
        required: true
        schema:
          title: Settingid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Delete Setting
      tags:
      - Settings
      x-accepts:
      - application/json
    get:
      description: Get the a specific setting from the database
      operationId: get_setting
      parameters:
      - explode: false
        in: path
        name: settingId
        required: true
        schema:
          title: Settingid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Setting
      tags:
      - Settings
      x-accepts:
      - application/json
    put:
      description: Update a specific setting in the database if it exists
      operationId: update_setting
      parameters:
      - explode: false
        in: path
        name: settingId
        required: true
        schema:
          title: Settingid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SettingBody'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Update Setting
      tags:
      - Settings
      x-content-type: application/json
      x-accepts:
      - application/json
  /llm/settings:
    get:
      description: Get the list of the Large Language Models
      operationId: get_llms_settings
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Get Llms Settings
                type: object
          description: Successful Response
      summary: Get Llms Settings
      tags:
      - Large Language Model
      x-accepts:
      - application/json
  /llm/settings/{languageModelName}:
    get:
      description: Get settings and schema of the specified Large Language Model
      operationId: get_llm_settings
      parameters:
      - explode: false
        in: path
        name: languageModelName
        required: true
        schema:
          title: Languagemodelname
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Get Llm Settings
                type: object
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Llm Settings
      tags:
      - Large Language Model
      x-accepts:
      - application/json
    put:
      description: Upsert the Large Language Model setting
      operationId: upsert_llm_setting
      parameters:
      - explode: false
        in: path
        name: languageModelName
        required: true
        schema:
          title: Languagemodelname
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              default:
                openai_api_key: your-key-here
              title: Payload
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Upsert Llm Setting
                type: object
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Upsert Llm Setting
      tags:
      - Large Language Model
      x-content-type: application/json
      x-accepts:
      - application/json
  /embedder/settings:
    get:
      description: Get the list of the Embedders
      operationId: get_embedders_settings
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Get Embedders Settings
                type: object
          description: Successful Response
      summary: Get Embedders Settings
      tags:
      - Embedder
      x-accepts:
      - application/json
  /embedder/settings/{languageEmbedderName}:
    get:
      description: Get settings and schema of the specified Embedder
      operationId: get_embedder_settings
      parameters:
      - explode: false
        in: path
        name: languageEmbedderName
        required: true
        schema:
          title: Languageembeddername
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Get Embedder Settings
                type: object
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Embedder Settings
      tags:
      - Embedder
      x-accepts:
      - application/json
    put:
      description: Upsert the Embedder setting
      operationId: upsert_embedder_setting
      parameters:
      - explode: false
        in: path
        name: languageEmbedderName
        required: true
        schema:
          title: Languageembeddername
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              default:
                openai_api_key: your-key-here
              title: Payload
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Upsert Embedder Setting
                type: object
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Upsert Embedder Setting
      tags:
      - Embedder
      x-content-type: application/json
      x-accepts:
      - application/json
  /plugins/:
    get:
      description: List available plugins
      operationId: get_available_plugins
      parameters:
      - explode: true
        in: query
        name: query
        required: false
        schema:
          title: Query
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Get Available Plugins
                type: object
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Available Plugins
      tags:
      - Plugins
      x-accepts:
      - application/json
  /plugins/upload:
    post:
      description: Install a new plugin from a zip file
      operationId: install_plugin
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_install_plugin'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Install Plugin
                type: object
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Install Plugin
      tags:
      - Plugins
      x-content-type: multipart/form-data
      x-accepts:
      - application/json
  /plugins/upload/registry:
    post:
      description: Install a new plugin from registry
      operationId: install_plugin_from_registry
      requestBody:
        content:
          application/json:
            schema:
              default:
                url: https://github.com/plugin-dev-account/plugin-repo
              title: Payload
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Install Plugin From Registry
                type: object
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Install Plugin From Registry
      tags:
      - Plugins
      x-content-type: application/json
      x-accepts:
      - application/json
  /plugins/toggle/{plugin_id}:
    put:
      description: Enable or disable a single plugin
      operationId: toggle_plugin
      parameters:
      - explode: false
        in: path
        name: plugin_id
        required: true
        schema:
          title: Plugin Id
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Toggle Plugin
                type: object
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Toggle Plugin
      tags:
      - Plugins
      x-accepts:
      - application/json
  /plugins/settings:
    get:
      description: Returns the settings of all the plugins
      operationId: get_plugins_settings
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Get Plugins Settings
                type: object
          description: Successful Response
      summary: Get Plugins Settings
      tags:
      - Plugins
      x-accepts:
      - application/json
  /plugins/settings/{plugin_id}:
    get:
      description: Returns the settings of a specific plugin
      operationId: get_plugin_settings
      parameters:
      - explode: false
        in: path
        name: plugin_id
        required: true
        schema:
          title: Plugin Id
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Get Plugin Settings
                type: object
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Plugin Settings
      tags:
      - Plugins
      x-accepts:
      - application/json
    put:
      description: Updates the settings of a specific plugin
      operationId: upsert_plugin_settings
      parameters:
      - explode: false
        in: path
        name: plugin_id
        required: true
        schema:
          title: Plugin Id
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              default:
                setting_a: some value
                setting_b: another value
              title: Payload
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Upsert Plugin Settings
                type: object
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Upsert Plugin Settings
      tags:
      - Plugins
      x-content-type: application/json
      x-accepts:
      - application/json
  /plugins/{plugin_id}:
    delete:
      description: Physically remove plugin.
      operationId: delete_plugin
      parameters:
      - explode: false
        in: path
        name: plugin_id
        required: true
        schema:
          title: Plugin Id
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Delete Plugin
                type: object
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Delete Plugin
      tags:
      - Plugins
      x-accepts:
      - application/json
    get:
      description: Returns information on a single plugin
      operationId: get_plugin_details
      parameters:
      - explode: false
        in: path
        name: plugin_id
        required: true
        schema:
          title: Plugin Id
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Get Plugin Details
                type: object
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Plugin Details
      tags:
      - Plugins
      x-accepts:
      - application/json
  /memory/recall:
    get:
      description: Search k memories similar to given text.
      operationId: recall_memories_from_text
      parameters:
      - description: Find memories similar to this text.
        explode: true
        in: query
        name: text
        required: true
        schema:
          description: Find memories similar to this text.
          title: Text
          type: string
        style: form
      - description: How many memories to return.
        explode: true
        in: query
        name: k
        required: false
        schema:
          default: 100
          description: How many memories to return.
          title: K
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Recall Memories From Text
                type: object
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Recall Memories From Text
      tags:
      - Memory
      x-accepts:
      - application/json
  /memory/collections:
    delete:
      description: Delete and create all collections
      operationId: wipe_collections
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Wipe Collections
                type: object
          description: Successful Response
      summary: Wipe Collections
      tags:
      - Memory
      x-accepts:
      - application/json
    get:
      description: Get list of available collections
      operationId: get_collections
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Get Collections
                type: object
          description: Successful Response
      summary: Get Collections
      tags:
      - Memory
      x-accepts:
      - application/json
  /memory/collections/{collection_id}:
    delete:
      description: Delete and recreate a collection
      operationId: wipe_single_collection
      parameters:
      - explode: false
        in: path
        name: collection_id
        required: true
        schema:
          title: Collection Id
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Wipe Single Collection
                type: object
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Wipe Single Collection
      tags:
      - Memory
      x-accepts:
      - application/json
  /memory/collections/{collection_id}/points:
    delete:
      description: Delete points in memory by filter
      operationId: delete_memory_points_by_metadata
      parameters:
      - explode: false
        in: path
        name: collection_id
        required: true
        schema:
          title: Collection Id
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              default: {}
              title: Metadata
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Delete Memory Points By Metadata
                type: object
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Delete Memory Points By Metadata
      tags:
      - Memory
      x-content-type: application/json
      x-accepts:
      - application/json
    post:
      description: Create a point in memory
      operationId: create_memory_point
      parameters:
      - explode: false
        in: path
        name: collection_id
        required: true
        schema:
          title: Collection Id
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemoryPointBase'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemoryPoint'
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Create Memory Point
      tags:
      - Memory
      x-content-type: application/json
      x-accepts:
      - application/json
  /memory/collections/{collection_id}/points/{point_id}:
    delete:
      description: Delete a specific point in memory
      operationId: delete_memory_point
      parameters:
      - explode: false
        in: path
        name: collection_id
        required: true
        schema:
          title: Collection Id
          type: string
        style: simple
      - explode: false
        in: path
        name: point_id
        required: true
        schema:
          title: Point Id
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Delete Memory Point
                type: object
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Delete Memory Point
      tags:
      - Memory
      x-accepts:
      - application/json
  /memory/conversation_history:
    delete:
      description: Delete the specified user's conversation history from working memory
      operationId: wipe_conversation_history
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Wipe Conversation History
                type: object
          description: Successful Response
      summary: Wipe Conversation History
      tags:
      - Memory
      x-accepts:
      - application/json
    get:
      description: Get the specified user's conversation history from working memory
      operationId: get_conversation_history
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Get Conversation History
                type: object
          description: Successful Response
      summary: Get Conversation History
      tags:
      - Memory
      x-accepts:
      - application/json
  /rabbithole/:
    post:
      description: |-
        Upload a file containing text (.txt, .md, .pdf, etc.). File content will be extracted and segmented into chunks.
        Chunks will be then vectorized and stored into documents memory.

        Note
        ----------
        `chunk_size`, `chunk_overlap` anad `metadata` must be passed as form data.
        This is necessary because the HTTP protocol does not allow file uploads to be sent as JSON.

        Example
        ----------
        ```
        content_type = "application/pdf"
        file_name = "sample.pdf"
        file_path = f"tests/mocks/{file_name}"
        with open(file_path, "rb") as f:
            files = {"file": (file_name, f, content_type)}

            metadata = {
                "source": "sample.pdf",
                "title": "Test title",
                "author": "Test author",
                "year": 2020,
            }
            # upload file endpoint only accepts form-encoded data
            payload = {
                "chunk_size": 128,
                "metadata": json.dumps(metadata)
            }

            response = requests.post(
                "http://localhost:1865/rabbithole/",
                files=files,
                data=payload
            )
        ```
      operationId: upload_file
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_upload_file'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Upload File
                type: object
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Upload File
      tags:
      - Rabbit Hole
      x-content-type: multipart/form-data
      x-accepts:
      - application/json
  /rabbithole/web:
    post:
      description: |-
        Upload a url. Website content will be extracted and segmented into chunks.
        Chunks will be then vectorized and stored into documents memory.
      operationId: upload_url
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UploadURLConfig'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Upload Url
      tags:
      - Rabbit Hole
      x-content-type: application/json
      x-accepts:
      - application/json
  /rabbithole/memory:
    post:
      description: Upload a memory json file to the cat memory
      operationId: upload_memory
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_upload_memory'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Upload Memory
                type: object
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Upload Memory
      tags:
      - Rabbit Hole
      x-content-type: multipart/form-data
      x-accepts:
      - application/json
  /rabbithole/allowed-mimetypes:
    get:
      description: Retrieve the allowed mimetypes that can be ingested by the Rabbit
        Hole
      operationId: get_allowed_mimetypes
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Get Allowed Mimetypes
                type: object
          description: Successful Response
      summary: Get Allowed Mimetypes
      tags:
      - Rabbit Hole
      x-accepts:
      - application/json
  /auth_handler/settings:
    get:
      description: Get the list of the AuthHandlers
      operationId: get_auth_handler_settings
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Get Auth Handler Settings
                type: object
          description: Successful Response
      summary: Get Auth Handler Settings
      tags:
      - AuthHandler
      x-accepts:
      - application/json
  /auth_handler/settings/{auth_handler_name}:
    get:
      description: Get the settings of a specific AuthHandler
      operationId: get_auth_handler_setting
      parameters:
      - explode: false
        in: path
        name: auth_handler_name
        required: true
        schema:
          title: Auth Handler Name
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Get Auth Handler Setting
                type: object
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Auth Handler Setting
      tags:
      - AuthHandler
      x-accepts:
      - application/json
    put:
      description: Upsert the settings of a specific AuthHandler
      operationId: upsert_authenticator_setting
      parameters:
      - explode: false
        in: path
        name: auth_handler_name
        required: true
        schema:
          title: Auth Handler Name
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              title: Payload
              type: object
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Upsert Authenticator Setting
                type: object
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Upsert Authenticator Setting
      tags:
      - AuthHandler
      x-content-type: application/json
      x-accepts:
      - application/json
components:
  schemas:
    AuthPermission:
      enum:
      - WRITE
      - EDIT
      - LIST
      - READ
      - DELETE
      title: AuthPermission
      type: string
    AuthResource:
      enum:
      - STATUS
      - MEMORY
      - CONVERSATION
      - SETTINGS
      - LLM
      - EMBEDDER
      - AUTH_HANDLER
      - USERS
      - UPLOAD
      - PLUGINS
      - STATIC
      title: AuthResource
      type: string
    Body_install_plugin:
      properties:
        file:
          format: binary
          title: File
          type: string
      required:
      - file
      title: Body_install_plugin
    Body_upload_file:
      properties:
        file:
          format: binary
          title: File
          type: string
        chunk_size:
          nullable: true
          type: integer
        chunk_overlap:
          nullable: true
          type: integer
        metadata:
          default: "{}"
          description: "Metadata to be stored with each chunk (e.g. author, category,\
            \ etc.). Since we are passing this along side form data, must be a JSON\
            \ string (use `json.dumps(metadata)`)."
          title: Metadata
          type: string
      required:
      - file
      title: Body_upload_file
    Body_upload_memory:
      properties:
        file:
          format: binary
          title: File
          type: string
      required:
      - file
      title: Body_upload_memory
    CatMessage:
      additionalProperties: {}
      description: |-
        Class for wrapping cat message

        Variables:
            content (str): cat message
            user_id (str): user id
      example:
        user_id: user_id
        why:
          input: input
          memory: "{}"
          model_interactions:
          - model_type: ""
            started_at: 6.027456183070403
            output_tokens: 1
            source: source
            reply: reply
            prompt: prompt
            input_tokens: 0
            ended_at: 5.962133916683182
          - model_type: ""
            started_at: 6.027456183070403
            output_tokens: 1
            source: source
            reply: reply
            prompt: prompt
            input_tokens: 0
            ended_at: 5.962133916683182
          intermediate_steps:
          - ""
          - ""
        type: chat
        content: content
      properties:
        content:
          title: Content
        user_id:
          title: User Id
        type:
          default: chat
          title: Type
        why:
          $ref: '#/components/schemas/CatMessage_why'
      required:
      - content
      - user_id
      title: CatMessage
    EmbedderModelInteraction:
      properties:
        model_type: {}
        source:
          default: recall
          title: Source
          type: string
        prompt:
          title: Prompt
          type: string
        input_tokens:
          title: Input Tokens
          type: integer
        started_at:
          title: Started At
          type: number
        reply:
          items:
            type: number
          type: array
      required:
      - input_tokens
      - prompt
      - reply
      title: EmbedderModelInteraction
    HTTPValidationError:
      example:
        detail:
        - msg: msg
          loc:
          - ValidationError_loc_inner
          - ValidationError_loc_inner
          type: type
        - msg: msg
          loc:
          - ValidationError_loc_inner
          - ValidationError_loc_inner
          type: type
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
      title: HTTPValidationError
    JWTResponse:
      example:
        access_token: access_token
        token_type: bearer
      properties:
        access_token:
          title: Access Token
          type: string
        token_type:
          default: bearer
          title: Token Type
          type: string
      required:
      - access_token
      title: JWTResponse
    LLMModelInteraction:
      example:
        model_type: ""
        started_at: 6.027456183070403
        output_tokens: 1
        source: source
        reply: reply
        prompt: prompt
        input_tokens: 0
        ended_at: 5.962133916683182
      properties:
        model_type: {}
        source:
          title: Source
          type: string
        prompt:
          title: Prompt
          type: string
        input_tokens:
          title: Input Tokens
          type: integer
        started_at:
          title: Started At
          type: number
        reply:
          title: Reply
          type: string
        output_tokens:
          title: Output Tokens
          type: integer
        ended_at:
          title: Ended At
          type: number
      required:
      - ended_at
      - input_tokens
      - output_tokens
      - prompt
      - reply
      - source
      title: LLMModelInteraction
    MemoryPoint:
      example:
        metadata: "{}"
        vector:
        - 0.8008281904610115
        - 0.8008281904610115
        id: id
        content: content
      properties:
        content:
          title: Content
          type: string
        metadata:
          default: {}
          title: Metadata
          type: object
        id:
          title: Id
          type: string
        vector:
          items:
            type: number
          type: array
      required:
      - content
      - id
      - vector
      title: MemoryPoint
    MemoryPointBase:
      example:
        metadata: "{}"
        content: content
      properties:
        content:
          title: Content
          type: string
        metadata:
          default: {}
          title: Metadata
          type: object
      required:
      - content
      title: MemoryPointBase
    MessageWhy:
      additionalProperties: {}
      description: |-
        Class for wrapping message why

        Variables:
            input (str): input message
            intermediate_steps (List): intermediate steps
            memory (dict): memory
            model_interactions (List[LLMModelInteraction | EmbedderModelInteraction]): model interactions
      example:
        input: input
        memory: "{}"
        model_interactions:
        - model_type: ""
          started_at: 6.027456183070403
          output_tokens: 1
          source: source
          reply: reply
          prompt: prompt
          input_tokens: 0
          ended_at: 5.962133916683182
        - model_type: ""
          started_at: 6.027456183070403
          output_tokens: 1
          source: source
          reply: reply
          prompt: prompt
          input_tokens: 0
          ended_at: 5.962133916683182
        intermediate_steps:
        - ""
        - ""
      properties:
        input:
          title: Input
        intermediate_steps:
          items: {}
          title: Intermediate Steps
        memory:
          title: Memory
        model_interactions:
          items:
            $ref: '#/components/schemas/Model_Interactions_inner'
          title: Model Interactions
      required:
      - input
      - intermediate_steps
      - memory
      - model_interactions
      title: MessageWhy
    SettingBody:
      example:
        name: name
        category: category
        value: "{}"
      properties:
        name:
          title: Name
          type: string
        value:
          $ref: '#/components/schemas/Value'
        category:
          nullable: true
          type: string
      required:
      - name
      - value
      title: SettingBody
    UploadURLConfig:
      additionalProperties: {}
      example:
        chunk_size: 0
        metadata: "{}"
        chunk_overlap: 6
        url: url
      properties:
        url:
          description: URL of the website to which you want to save the content
          title: Url
        chunk_size:
          $ref: '#/components/schemas/Chunk_Size'
        chunk_overlap:
          $ref: '#/components/schemas/Chunk_Overlap'
        metadata:
          default: {}
          description: "Metadata to be stored with each chunk (e.g. author, category,\
            \ etc.)"
          title: Metadata
      required:
      - url
      title: UploadURLConfig
    UserCreate:
      additionalProperties: {}
      example:
        password: password
        permissions:
          key:
          - WRITE
          - WRITE
        username: username
      properties:
        username:
          minLength: 2
          title: Username
        permissions:
          additionalProperties:
            items:
              $ref: '#/components/schemas/AuthPermission'
          default:
            CONVERSATION:
            - WRITE
            - EDIT
            - LIST
            - READ
            - DELETE
            MEMORY:
            - READ
            - LIST
            STATIC:
            - READ
            STATUS:
            - READ
          title: Permissions
        password:
          minLength: 5
          title: Password
      required:
      - password
      - username
      title: UserCreate
    UserCredentials:
      example:
        password: password
        username: username
      properties:
        username:
          title: Username
          type: string
        password:
          title: Password
          type: string
      required:
      - password
      - username
      title: UserCredentials
    UserResponse:
      example:
        permissions:
          key:
          - WRITE
          - WRITE
        id: id
        username: username
      properties:
        username:
          minLength: 2
          title: Username
          type: string
        permissions:
          additionalProperties:
            items:
              $ref: '#/components/schemas/AuthPermission'
          default:
            CONVERSATION:
            - WRITE
            - EDIT
            - LIST
            - READ
            - DELETE
            MEMORY:
            - READ
            - LIST
            STATIC:
            - READ
            STATUS:
            - READ
          title: Permissions
        id:
          title: Id
          type: string
      required:
      - id
      - username
      title: UserResponse
    UserUpdate:
      additionalProperties: {}
      example:
        password: password
        permissions:
          key:
          - WRITE
          - WRITE
        username: username
      properties:
        username:
          minLength: 2
          title: Username
          type: string
        permissions:
          additionalProperties:
            items:
              $ref: '#/components/schemas/AuthPermission'
          title: Permissions
        password:
          minLength: 4
          title: Password
      title: UserUpdate
    ValidationError:
      example:
        msg: msg
        loc:
        - ValidationError_loc_inner
        - ValidationError_loc_inner
        type: type
      properties:
        loc:
          items:
            $ref: '#/components/schemas/ValidationError_loc_inner'
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
    CatMessage_why:
      anyOf:
      - $ref: '#/components/schemas/MessageWhy'
      - nullable: true
    Model_Interactions_inner:
      anyOf:
      - $ref: '#/components/schemas/LLMModelInteraction'
      - $ref: '#/components/schemas/EmbedderModelInteraction'
    Value:
      anyOf:
      - type: object
      - items: {}
        type: array
      title: Value
    Chunk_Size:
      anyOf:
      - {}
      - {}
      description: Maximum length of each chunk after the document is split (in tokens)
      title: Chunk Size
    Chunk_Overlap:
      anyOf:
      - {}
      - {}
      description: Chunk overlap (in tokens)
      title: Chunk Overlap
    ValidationError_loc_inner:
      anyOf:
      - type: string
      - nullable: true
        type: integer

